version: 2
aliases:
  - &docker_image circleci/python:3.6.2-stretch
  - &dependencies
    name: Make virtualenv and install dependencies
    command: |
      python3 -m venv ~/venv
      echo ". ~/venv/bin/activate" >> $BASH_ENV
      source $BASH_ENV
      make dependencies


jobs:
  lint:
    docker:
      - image: *docker_image
    steps:
      - checkout
      - run:
          <<: *dependencies
      - run: make validate
  test:
    docker:
      - image: *docker_image
    environment:
      TEST_REPORTS: /tmp/test-reports
    steps:
      - checkout
      - run:
          name: Install postgres
          command: |
            sudo apt-get update && sudo apt install postgresql postgresql-contrib
      - run:
          <<: *dependencies
      - run: make test_single_version
      - store_test_results:
          path: /tmp/test-reports
      - store_artifacts:
          path: /tmp/test-reports

  deploy:
    docker:
      - image: *docker_image
    steps:
      - checkout
      - run:
          <<: *dependencies
      - run: pip install -q -r deploy_requirements.txt
      - add_ssh_keys:
          fingerprints:
            - "f9:ef:5e:40:d5:ed:e3:86:a1:18:3e:09:85:93:ef:3a" # CAN I DO THIS?? prob not
      - run: python3 deploy.py prod

workflows:
  version: 2
  checks_and_deploy:
    jobs:
      - lint
      - test
      - deploy:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - master