version: 2
aliases:
  - &docker_image circleci/python:3.6.2-stretch
  - &dependencies
    name: Make virtualenv and install dependencies
    command: |
      python3 -m venv ~/venv
      echo ". ~/venv/bin/activate" >> $BASH_ENV
      source $BASH_ENV
      make dependencies


jobs:
  lint:
    docker:
      - image: *docker_image
    steps:
      - checkout
      - run:
          <<: *dependencies
      - run: make validate
  test:
    docker:
      - image: *docker_image
    environment:
      TEST_REPORTS: /tmp/test-reports
    steps:
      - checkout
      - run:
          name: Install postgres
          command: |
            sudo apt-get update && sudo apt install postgresql postgresql-contrib
      - run:
          <<: *dependencies
      - run: make test_single_version
      - store_test_results:
          path: /tmp/test-reports
      - store_artifacts:
          path: /tmp/test-reports


workflows:
  version: 2
  checks_and_deploy:
    jobs:
      - lint
      - test
